name: docs
on:
  push:
    branches:
      - main
      - v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike
      - run: git config user.name "GitHub Actions Bot"
      - run: git config user.email "github-actions-bot@marvinweber.net"
      - run: mike deploy --force --update-alias $(cat kpsimplebackup.version | grep KPSimpleBackup | sed -r "s/KPSimpleBackup\:([0-9]+)\.([0-9]+)\.([0-9])/\1.\2/") latest
